name: Rust Build

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-feature=+crt-static"

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    
    - name: 安装 Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.67.1  # 修改为指定版本
        targets: i686-pc-windows-msvc, x86_64-pc-windows-msvc
        components: rust-src
        
    - name: 缓存依赖
      uses: Swatinem/rust-cache@v2
      
    - name: 构建 x64 版本
      run: cargo build --release --target x86_64-pc-windows-msvc
      
    - name: 构建 x32 版本
      run: cargo build --release --target i686-pc-windows-msvc
      
    - name: 准备发布文件
      run: |
        mkdir release
        copy target/x86_64-pc-windows-msvc/release/auto_backup.exe release/auto_backup_x64.exe
        copy target/i686-pc-windows-msvc/release/auto_backup.exe release/auto_backup_x32.exe
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: auto_backup
        path: release/

    - name: 创建发布
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/auto_backup_x64.exe
          release/auto_backup_x32.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}